language: python
python:
  - "3.8"
  - "3.9"
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1, PyPy 7.1.1-beta0
# command to install dependencies
before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="pureBeurre.settings"

services:
  - postgresql
# command to run tests
script:
  - pytest