# Generated by Django 3.2.7 on 2021-09-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pnns_groups_1',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='pnns_groups_1',
        ),
        migrations.AddField(
            model_name='product',
            name='pnns_groups_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
