# Generated by Django 3.2.7 on 2021-10-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211014_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='user',
        ),
    ]
