# Generated by Django 3.2.7 on 2021-10-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user',
            new_name='user_id',
        ),
    ]
